### ISSUE TITLE
Kafka streams errors out "Missing source topic" after upgrading from 1.0.0

### ISSUE THREAD

**Issue by prasanna-palle** [confluentinc/kafka-streams-examples#357]
Hello team,

I have recently upgraded from 1.0.0 to 2.3.x. I have a kafka streams application whose topology is built as :

source topic -> Processor1 -> output topic 1 -> Processor2 -> output topic 2 -> Processor 3 ....etc

Only source topic was always existent before application started and the remaining topics were created as the processing goes on or during spinning up the application, as part of 1.0.0.

But the new version errors out on "Missing source topic  output topic 2   durign assignment. Returning error INCOMPLETE_SOURCE_TOPIC_METADATA."

The auto-create-topics is set to true. So shouldn't the streams take care of creating topics and waiting until they are available? (atleast for the intermediate topics)

Did anything change as part of configuration after 1.x in Kafka streams that should be included?

I currently am setting : StreamsConfig.APPLICATION_ID_CONFIG, StreamsConfig.BOOTSTRAP_SERVERS_CONFIG, StreamsConfig.DEFAULT_KEY_SERDE_CLASS_CONFIG, StreamsConfig.DEFAULT_VALUE_SERDE_CLASS_CONFIG, StreamsConfig.NUM_STREAM_THREADS_CONFIG, StreamsConfig.DEFAULT_TIMESTAMP_EXTRACTOR_CLASS_CONFIG as part of KafkaStreamsConfiguration.

Thanks.

**Comment by mjsax** [comment]
As explained in the docs, input and output topic are considers "user topics" and you need to create those topics upfront: https://docs.confluent.io/current/streams/developer-guide/manage-topics.html

In older versions, auto-create-topic might still trigger but it was always an undesired side effect and this "bug" was fixed in newer versions. Thus, in newer versions if input topics don't exist, you get the error you describe and the app shuts down.

Also note that internal topics like repartition topic and changelog topics will still be created for you. However, Kafka Streams does _not_ rely on auto-create-topic for this, but an explicit create-topic-request is sent to the cluster.
